import { http } from "@/api/client/http";

export type ListFileByProjectGroupResponse = Record<string, any[]>;

export type PageRequest<TQuery extends object = Record<string, unknown>> = TQuery & {
	page?: number;
	page_size?: number;
};

export interface PageResponse<TItem> {
	data: TItem[];
	page: number;
	page_size: number;
	total: number;
}

export interface DatasetItem {
	id: string;
	dataset_name: string;
	description: string;
	metadata: string;
	created_at: string;
	updated_at: string;
}

export interface DatasetFileItem {
	id: string;
	file_id: string;
	file_name: string;
	path: string;
	format: string;
	size: number;
	analysis_node_id: string;
	md5: string;
	storage: string;
	description: string;
	created_at: string;
	updated_at: string;
	dataset_id: string;
	dataset_name: string;
	role: string;
}

export interface AssayDetailItem {
	id: string;
	sample_id: string;
	assay_type: string;
	platform: string;
	library_id: string;
	metadata: string;
	created_at: string;
	updated_at: string;
}

// AssayItem is the read model of the paged assay API: it carries the owning
// dataset on top of the plain assay entity, plus the owning sample/subject
// labels joined in by the backend so the table needs no extra lookup.
export interface AssayItem extends AssayDetailItem {
	dataset_id: string;
	dataset_name: string;
	sample_name: string;
	// subject_name is the owning Subject's human-readable display name
	// (go_subject.subject_name).
	subject_name: string;
}

// SubjectItem is a donor / individual (go_subject). subject_key is the business key
// (e.g. "mouse-001"), subject_name is a human-readable display name (Chinese or
// with spaces); neither has to be unique, id is the int64 primary key.
export interface SubjectItem {
	id: string;
	subject_key: string;
	subject_name: string;
	species: string;
	strain: string;
	sex: string;
	age: string;
	metadata: string;
	created_at: string;
	updated_at: string;
}

// SampleItem is one biological sample taken from a Subject (go_sample).
// sample_key is the business number; subject_id is the owning subject's PK.
export interface SampleItem {
	id: string;
	sample_key: string;
	sample_name: string;
	subject_id: string;
	tissue: string;
	cell_type: string;
	collection_time?: string | null;
	metadata: string;
	description: string;
	created_at: string;
	updated_at: string;
}

// SampleWithSubjectItem is what /data/sample/page returns: a Sample joined with
// its Subject's business name/species so the picker can show them directly.
// `subject_id` (inherited) stays the owning subject's PK.
export interface SampleWithSubjectItem extends SampleItem {
	subject_name: string;
	species: string;
}

// DatasetAssayItem binds an Assay into a Dataset (go_dataset_assay).
// `role` is the assay's role inside the binding; analysis form inputs with
// input_type=assay match it against their resolver.accept_formats (same
// convention as DatasetFile.role for files).
export interface DatasetAssayItem {
	id: string;
	dataset_id: string;
	assay_id: string;
	role: string;
	created_at: string;
}

export interface DatasetPageQuery {
	project_id?: string;
	id?: string;
	dataset_name?: string;
	description?: string;
	metadata?: string;
}

export interface DatasetFilePageQuery {
	// project_id: string;
	id?: string;
	file_id?: string;
	file_name?: string;
	path?: string;
	format?: string;
	size?: number;
	md5?: string;
	storage?: string;
	description?: string;
	dataset_id?: string;
	dataset_name?: string;
	role?: string[];
}

export interface AssayPageQuery {
	// project_id: string;
	id?: string;
	sample_id?: string;
	assay_type?: string;
	platform?: string;
	library_id?: string;
	metadata?: string;
	dataset_id?: string;
	dataset_name?: string;
}

export interface SubjectPageQuery {
	subject_key?: string;
	subject_name?: string;
	species?: string;
	strain?: string;
	sex?: string;
}

export interface SamplePageQuery {
	sample_key?: string;
	sample_name?: string;
	subject_id?: string;
	tissue?: string;
	cell_type?: string;
}

// SaveSubjectRequest payload for /data/subject/create and /data/subject/update.
// subject_key is the business key (e.g. "mouse-001") and is required (not unique);
// subject_name is an optional human-readable display name (e.g. "小鼠 001");
// the PK is generated by the backend. Fields left undefined are omitted from
// the request body.
export interface SaveSubjectRequest {
	subject_key: string;
	subject_name?: string;
	species?: string;
	strain?: string;
	sex?: string;
	age?: string;
	metadata?: string;
}

// SaveSampleRequest payload for /data/sample/create and /data/sample/update.
// sample_key is the unique business number; subject_id is the owning subject's
// PK (sent as a string, backend int64).
export interface SaveSampleRequest {
	sample_key: string;
	sample_name?: string;
	subject_id: string;
	tissue?: string;
	cell_type?: string;
	collection_time?: string | null;
	metadata?: string;
	description?: string;
}

// SaveAssayRequest payload for /data/assay/create and /data/assay/update.
export interface SaveAssayRequest {
	sample_id: string;
	assay_type?: string;
	platform?: string;
	library_id?: string;
	metadata?: string;
}

// CreateFileRequest payload for /data/file/create. assay_id binds the file to its
// owning assay (a file belongs to at most one assay); omit it for files that are
// only attached to a dataset. file_key is the key an analysis form input maps
// onto its resolver.accept_formats.
export interface CreateFileRequest {
	file_id?: string;
	file_name?: string;
	path: string;
	format?: string;
	assay_id?: string;
	file_key?: string;
	analysis_node_id?: string;
	description?: string;
}

export interface AddFileToDatasetRequest {
	dataset_id: string;
	path: string;
	role?: string;
	file_name?: string;
	is_copy?: boolean;
	is_prefix?: boolean;
	analysis_node_id?: string;
	// "data" resolves the path under base_dir/data/<project_id>, "analysis" expects an absolute path
	source?: string;
}

export interface AddFileToDatasetResponse {
	file: Record<string, unknown>;
	dataset_file: Record<string, unknown>;
}

export interface UpdateFileRequest {
	id: string;
	// path re-points the record at another physical file. Omit it to keep the
	// stored path (the backend only writes non-empty values).
	path?: string;
	file_name?: string;
	description?: string;
	format?: string;
	storage?: string;
	assay_id?: string;
	file_key?: string;
}

export interface DeleteFileRequest {
	id: string;
}

export const listFileByProjectGroupApi = (projectId: string) => {
	return http.get<ListFileByProjectGroupResponse>(
		`/data/file/list-by-project-group?project_id=${encodeURIComponent(projectId)}`
	);
};

export interface CreateDatasetRequest {
	dataset_name: string;
	description?: string;
	metadata?: string;
}

export interface UpdateDatasetRequest extends CreateDatasetRequest {
	id: string;
}

export interface DeleteDatasetRequest {
	id: string;
}

export const pageDatasetByProjectApi = (payload: PageRequest<DatasetPageQuery>) => {
	return http.post<PageResponse<DatasetItem>>("/data/dataset/list-by-project-page", payload);
};

export const createDatasetApi = (payload: CreateDatasetRequest) => {
	return http.post<DatasetItem>("/data/dataset/create", payload);
};

export const updateDatasetApi = (payload: UpdateDatasetRequest) => {
	return http.post<{ message: string }>("/data/dataset/update", payload);
};

export const deleteDatasetApi = (payload: DeleteDatasetRequest) => {
	return http.post<{ message: string }>("/data/dataset/delete", payload);
};

export interface EnsureDatasetDirResponse {
	path: string;
}

export const ensureDatasetDirApi = (payload: { id: string }) => {
	return http.post<EnsureDatasetDirResponse>("/data/dataset/ensure-dir", payload);
};

export const pageFileByProjectApi = (payload: PageRequest<DatasetFilePageQuery>) => {
	return http.post<PageResponse<DatasetFileItem>>("/data/file/list-by-project-page", payload);
};

export const pageAssayByProjectApi = (payload: PageRequest<AssayPageQuery>) => {
	return http.post<PageResponse<AssayItem>>("/data/assay/list-by-project-page", payload);
};

// ---------------------------------------------------------------------------
// Assay create / update / read
// ---------------------------------------------------------------------------

export const getAssayApi = (id: string) => {
	return http.get<AssayDetailItem>(`/data/assay/get?id=${encodeURIComponent(id)}`);
};

export const createAssayApi = (payload: SaveAssayRequest) => {
	return http.post<AssayDetailItem>("/data/assay/create", payload);
};

export const updateAssayApi = (payload: SaveAssayRequest & { id: string }) => {
	return http.post<{ message: string }>("/data/assay/update", payload);
};

// Deleting an assay also removes the files it owns and its dataset binding.
export const deleteAssayApi = (payload: { id: string }) => {
	return http.post<{ message: string }>("/data/assay/delete", payload);
};

// ---------------------------------------------------------------------------
// Assay files (go_file.assay_id: a file is owned by at most one assay)
// ---------------------------------------------------------------------------

export const listFileByAssayApi = (assayId: string) => {
	return http.get<DataFileItem[]>(
		`/data/file/list-by-assay?assay_id=${encodeURIComponent(assayId)}`
	);
};

export const createFileApi = (payload: CreateFileRequest) => {
	return http.post<DataFileItem>("/data/file/create", payload);
};

// ---------------------------------------------------------------------------
// DatasetAssay (Assay -> Dataset binding)
// ---------------------------------------------------------------------------

export const createDatasetAssayApi = (payload: {
	dataset_id: string;
	assay_id: string;
	role?: string;
}) => {
	return http.post<DatasetAssayItem>("/data/dataset-assay/create", payload);
};

export const updateDatasetAssayApi = (payload: {
	id: string;
	dataset_id: string;
	assay_id: string;
	role?: string;
}) => {
	return http.post<{ message: string }>("/data/dataset-assay/update", payload);
};

// Returns null when the assay is not bound to any dataset yet.
export const getDatasetAssayByAssayApi = (assayId: string) => {
	return http.get<DatasetAssayItem | null>(
		`/data/dataset-assay/get-by-assay?assay_id=${encodeURIComponent(assayId)}`
	);
};

// ---------------------------------------------------------------------------
// Subject
// ---------------------------------------------------------------------------

export const pageSubjectApi = (payload: PageRequest<SubjectPageQuery>) => {
	return http.post<PageResponse<SubjectItem>>("/data/subject/page", payload);
};

export const listSubjectApi = () => {
	return http.get<SubjectItem[]>("/data/subject/list");
};

export const getSubjectApi = (id: string) => {
	return http.get<SubjectItem>(`/data/subject/get?id=${encodeURIComponent(id)}`);
};

export const createSubjectApi = (payload: SaveSubjectRequest) => {
	return http.post<SubjectItem>("/data/subject/create", payload);
};

export const updateSubjectApi = (payload: SaveSubjectRequest & { id: string }) => {
	return http.post<SubjectItem>("/data/subject/update", payload);
};

// The backend returns 409 while the subject still owns samples.
export const deleteSubjectApi = (payload: { id: string }) => {
	return http.post<{ message: string }>("/data/subject/delete", payload);
};

// ---------------------------------------------------------------------------
// Sample
// ---------------------------------------------------------------------------

export const pageSampleApi = (payload: PageRequest<SamplePageQuery>) => {
	return http.post<PageResponse<SampleWithSubjectItem>>("/data/sample/page", payload);
};

export const listSampleApi = () => {
	return http.get<SampleItem[]>("/data/sample/list");
};

export const getSampleApi = (id: string) => {
	return http.get<SampleItem>(`/data/sample/get?id=${encodeURIComponent(id)}`);
};

export const createSampleApi = (payload: SaveSampleRequest) => {
	return http.post<SampleItem>("/data/sample/create", payload);
};

export const updateSampleApi = (payload: SaveSampleRequest & { id: string }) => {
	return http.post<SampleItem>("/data/sample/update", payload);
};

// The backend returns 409 while the sample still owns assays.
export const deleteSampleApi = (payload: { id: string }) => {
	return http.post<{ message: string }>("/data/sample/delete", payload);
};

export const addFileToDatasetApi = (payload: AddFileToDatasetRequest) => {
	return http.post<AddFileToDatasetResponse>("/data/dataset-file/add-file", payload);
};

export const updateFileApi = (payload: UpdateFileRequest) => {
	return http.post<{ message: string }>("/data/file/update", payload);
};

export const deleteFileApi = (payload: DeleteFileRequest) => {
	return http.post<{ message: string }>("/data/file/delete", payload);
};

export interface UpdateDatasetFileRequest {
	dataset_id: string;
	file_id: string;
	role: string;
}

export const updateDatasetFileApi = (payload: UpdateDatasetFileRequest) => {
	return http.post<{ message: string }>("/data/dataset-file/update", payload);
};

export interface DataFileItem {
	id: string;
	file_id: string;
	file_name: string;
	path: string;
	format: string;
	// assay_id is the owning assay's PK; empty when the file is not owned by any
	// assay (dataset-only attachment).
	assay_id: string;
	// file_key (go_file.file_key) is the key this file fills inside its assay;
	// analysis form inputs map it onto their resolver.accept_formats keys.
	file_key: string;
	size: number;
	md5: string;
	storage: string;
	description: string;
	created_at: string;
	updated_at: string;
}

export const getFileApi = (id: string) => {
	return http.get<DataFileItem>(`/data/file/get?id=${encodeURIComponent(id)}`);
};
